### ISSUE TITLE
More information in the automated commit messages

### ISSUE THREAD

**Issue by asmeurer** [drdoctr/doctr#105]
It would be useful to put more information in the automated commit messages, like a link to the Travis build, and maybe some of the configuration info.

**Comment by gforsyth** [comment]
That's a great idea.  Just a heads up that I have my quals this week and early next, so I'm going to be AFK until Wednesday-ish.

**Comment by asmeurer** [comment]
It also should put the commit hash, so that GitHub will hotlink it and you can see what it was built off of. Just make sure to not use the special merge commit that only appears on Travis.
