### ISSUE TITLE
delete public Key by default ?

### ISSUE THREAD

**Issue by Carreau** [drdoctr/doctr#112]
The configure process says:

```
================== You should now do the following ==================

1. Commit the file github_deploy_key.enc.
The file github_deploy_key.pub contains the public deploy key for GitHub. It
does not need to be committed.
```

Is there any reason to keep it ? Would that be confusing to users ?

Would it be better to delete, leave as an option to keep it (it's cheap to regenerate), and say something along the lines:
-  The public deploy key has been activated on github (see `<url>`),  and the local version erased.

**Comment by asmeurer** [comment]
Yeah it really should. If you choose --no-upload-key and lose the terminal output you can get it from the file, but if that happens you could also just rerun doctr configure.
