### ISSUE TITLE
Check for travis repo before generating keys.

### ISSUE THREAD

**Issue by Carreau** [drdoctr/doctr#114]
Otherwise it will just fail and you'll have to regenerate. 

It's a small optimisation though, that will mostly affect users that make typos.

Note that github is not case sensitive for usernames, travis is so for example, I regularly get into trouble when I write my username lowercase and it involves travis.

**Comment by asmeurer** [comment]
I agree. Do you know how to do it?

**Comment by Carreau** [comment]
> I agree. Do you know how to do it?

Not from the top of my head. Right now I'm just filling in issues when I think about stuff before forgetting. 
I get back on that later.
