### ISSUE TITLE
Project using doctr

### ISSUE THREAD

**Issue by asmeurer** [drdoctr/doctr#115]
Could be useful to add a list to the docs. Right now, SymPy and conda are using it.

**Comment by gforsyth** [comment]
Should we throw this in the README?

**Comment by scopatz** [comment]
I would be nice to have xonsh use doctr too

**Comment by gforsyth** [comment]
I would very much like to have that -- one question related to #29 would be to have separate dev docs and release docs.  Or we could just bake that in to the `.travis.yml` as @asmeurer suggested there.

**Comment by scopatz** [comment]
Yeah, I envisoned that doctr would be used for dev docs, and our release docs, we would handle separately (though release.xsh)

**Comment by asmeurer** [comment]
Either the README or a new page in the docs.

**Comment by asmeurer** [comment]
https://github.com/drdoctr/doctr/pull/116
