### ISSUE TITLE
Question: docs in PR

### ISSUE THREAD

**Issue by rainwoodman** [drdoctr/doctr#117]
Is it possible to build and deploy a PR with doctr?

**Comment by asmeurer** [comment]
Yes, but *only* if the PR is on a branch from the same repo. It is impossible to deploy from a PR from a fork, because Travis doesn't allow encrypted environment variables from forks. See https://drdoctr.github.io/doctr/recipes.html#deploy-docs-from-any-branch. Let me know if that document could be improved.

**Comment by jorisvandenbossche** [comment]
@asmeurer I just tried this on the pandas website repo, and didn't succeed.

I added what was specified in the docs: https://github.com/pandas-dev/pandas-website/commit/5ade6614caaab706ca650599e734a0326dbf4099. 
Which seems to work, but on travis I still get the message "Don't have permission to push." (see bottom of https://travis-ci.org/pandas-dev/pandas-website/builds/216352369)

It is from a branch on the repo itself, not a fork.

**Comment by gforsyth** [comment]
Hey @jorisvandenbossche -- sorry about that! It looks like a recent refactor might have nuked that piece of functionality -- I'll try to put in a fix later today.

**Comment by gforsyth** [comment]
Hey @jorisvandenbossche, I put in a fix and just pushed a new release, so if you restart that build it should work this time

**Comment by jorisvandenbossche** [comment]
I can confirm it now works. Thanks a lot for the quick fix!

**Comment by gforsyth** [comment]
Woohoo! We aim to please.

**Comment by asmeurer** [comment]
Let us know if you hit any other snags or have any feature requests.
