### ISSUE TITLE
"summary" and "description" fields on pypi should be switched around

### ISSUE THREAD

**Issue by cmihai** [drdoctr/doctr#119]
A package's summary should be a short one-liner which gives people an idea what the package is about. However, when you do `pip search doctr`, you get a unreadable wall of text, with the formatting broken and the newlines removed. The wall of text should go into the `description` field, which preserves the formatting.

**Comment by gforsyth** [comment]
Thanks for reporting @cmihai -- I'm fixing this up now and we'll push a microrelease to sort it out on PyPi

**Comment by asmeurer** [comment]
Aaaah. I feel dumb. I changed this, but completely forgot to actually check pypi to see if it worked right.
