### ISSUE TITLE
Run almost all doctr steps on PR

### ISSUE THREAD

**Issue by mariusvniekerk** [drdoctr/doctr#125]
The only thing doctr shouldn't do is upload to gh-pages.

If, as part of your build, you modify your source tree, for example, doctr will refuse to do checkouts for it.  The same happens for incorrect file permissions (say arising from running sphinx inside a docker container).

Right now doctr just skips when doing PR builds it seems.  This means that these kinds of failures are not detected at the PR level and happen only when TravisCI is doing the push build.

For example  
- https://travis-ci.org/MaxPoint/spylon/builds/160663846
- https://travis-ci.org/MaxPoint/spylon/builds/160656976

By running everything but the actual git push that doctr does we can minimize this friction.

**Comment by asmeurer** [comment]
I *think* this is easy, but need to check. If it is, the fix at https://github.com/drdoctr/doctr/pull/126 should work.
