### ISSUE TITLE
Change --gh-pages-docs default

### ISSUE THREAD

**Issue by asmeurer** [drdoctr/doctr#128]
It's a backwards incompatible change, but `--gh-pages-docs` defaulting to `docs` is not great. `.` is probably what people expect.  Maybe we should make it a required argument. 

CC @ocefpaf

**Comment by gforsyth** [comment]
I think it's reasonable to change it to `.`

**Comment by gforsyth** [comment]
We could make it a required argument and make the helper text to be pasted into the `.travis.yml` `--gh-pages-docs .` as the default?

**Comment by ocefpaf** [comment]
I do not know the reasons to deploy to `docs`, and I am fine with https://github.com/drdoctr/doctr/issues/128#issuecomment-254960672 solution, but maybe the project is still young and a backwards incompatible change is not that bad...

**Comment by asmeurer** [comment]
If it's required it really ought to be the argument to `doctr deploy`, like `doctr deploy .`.

**Comment by gforsyth** [comment]
Done in #157.
