### ISSUE TITLE
Clarify docs that doctr is not only for sphinx

### ISSUE THREAD

**Issue by gforsyth** [drdoctr/doctr#129]

**Comment by asmeurer** [comment]
I guess this comes from the comment about SPHINXOPTS (maybe the misconception come from other places than the docs too). I'll add a note there.

**Comment by gforsyth** [comment]
I had also written that it was for "sphinx docs" in the description box -- changed that this morning

**Comment by asmeurer** [comment]
Ah.

**Comment by asmeurer** [comment]
I changed it again, to match what it says at the top of the README. Doctr doesn't do anything with building docs, just deploying them.
