### ISSUE TITLE
.travis.yml as a config file ?

### ISSUE THREAD

**Issue by Carreau** [drdoctr/doctr#136]
Yo, 

Not that I don't like passing lots of option to doctr on `.travis.yml` nor that I dislike things that are not meta enough... but... 

It occurred to me that doctr run on travis, so there is a high chance that a `.travis.yml` file is present. 
Travis ignore keys it does not know so what about a `doctr` key that would store config ?

**Comment by asmeurer** [comment]
I didn't know that. I'm ambivalent about the idea (meaning I won't implement it myself, but I'll accept a PR).

**Comment by gforsyth** [comment]
Implemented in #137.  Thanks, @Carreau !
