### ISSUE TITLE
auth issue when creating gh-pages branch

### ISSUE THREAD

**Issue by gforsyth** [drdoctr/doctr#145]
`travis.create_gh_pages` creates an orphan `gh-pages` branch with a `.nojekyll` file but it can't push this to the remote unless it's authenticated.

if there is no `gh-pages` branch then doctr will return a nonzero exit code when built on a PR since `canpush` will be set to `False`.

probably can just wrap all of the creation stuff in an `if canpush` block

**Comment by asmeurer** [comment]
Same issue seen at https://travis-ci.org/sea-mat/sea-mat/builds/189453991.
