### ISSUE TITLE
don't run git config --global if not on travis.

### ISSUE THREAD

**Issue by Carreau** [drdoctr/doctr#173]
Like.... if users run things locally to test.
because after a week you realize that all the commits you did are not your anymore on GH. (and likely screwed blame of projects your work on).

**Comment by asmeurer** [comment]
Ouch did that happen to you? `doctr deploy` should never do anything if not on Travis, unless `--force` is used.

**Comment by Carreau** [comment]
> Ouch did that happen to you? doctr deploy should never do anything if not on Travis, unless --force is used.

Unsure when. Not too much damage, I was not super active. I'll still add a check in `setup_GitHub`. I might have ran `py.test` locally, or something else that triggered this code.

**Comment by asmeurer** [comment]
The tests definitely shouldn't be running that code either.

**Comment by pelson** [comment]
Ideally, doctr would just the existing name/email configured, and only set them to fallback options if it really needs to. This would also mean that on Travis we can set the author before calling doctr if we want full control.

**Comment by asmeurer** [comment]
@pelson I opened a new issue for that https://github.com/drdoctr/doctr/issues/194.

**Comment by pelson** [comment]
Just realised I can override the configured values with [Git environment variables](https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables). The following ensures the commit author is the author of the incoming build:

```
export GIT_AUTHOR_NAME=$(git --no-pager show -s --format='%an' HEAD)
export GIT_AUTHOR_EMAIL=$(git --no-pager show -s --format='%ae' HEAD)
```

(the git committer remains "doctr", which is perfect)

**Comment by asmeurer** [comment]
Maybe we should just document this? I'm not fully understanding your use-case.

**Comment by pelson** [comment]
> I'm not fully understanding your use-case.

I want to control who the git author is (but not the git committer), so that I can correctly attribute the author from where the change came. In my example above, I'm treating the author of the commit that triggered travis to be the author of the doctr commit.

Just documenting it works well for me.

**Comment by asmeurer** [comment]
https://github.com/drdoctr/doctr/pull/216 should fix this. Open a new issue if you are still seeing doctr deploy messing with your local stuff without --force.
