### ISSUE TITLE
KeyError: 'deploy_directory'

### ISSUE THREAD

**Issue by ocefpaf** [drdoctr/doctr#179]
I am getting the following error when using `doctr configure --no-upload-key`:

```
Traceback (most recent call last):
  File "/home/filipe/miniconda3/envs/GSWc/bin/doctr", line 6, in <module>
    sys.exit(doctr.__main__.main())
  File "/home/filipe/miniconda3/envs/GSWc/lib/python3.6/site-packages/doctr/__main__.py", line 393, in main
    return process_args(get_parser(config=config))
  File "/home/filipe/miniconda3/envs/GSWc/lib/python3.6/site-packages/doctr/__main__.py", line 211, in process_args
    return args.func(args, parser)
  File "/home/filipe/miniconda3/envs/GSWc/lib/python3.6/site-packages/doctr/__main__.py", line 379, in configure
    """.format(options=options, N=N)))
KeyError: 'deploy_directory'
```

Am I doing something wrong?

**Comment by asmeurer** [comment]
Looks like we forgot to add `deploy_directory` to the format call. I'm not clear what it should be, though. We don't ask about it, so it should just default to `.` I think. Or `<deploy directory>`. @gforsyth ?

**Comment by gforsyth** [comment]
I was just typing out the same thing.  I think `<deploy directory>` works

**Comment by asmeurer** [comment]
Incidentally, @ocefpaf, this error happens at the very end of `doctr configure`, so it all still worked. You just didn't get the helpful message at the end telling you what to add to .travis.yml.

**Comment by gforsyth** [comment]
@asmeurer -- should we do a microrelease for this? seems like an annnoyance for new users

**Comment by ocefpaf** [comment]
That was fast! Thanks!!

> You just didn't get the helpful message at the end telling you what to add to .travis.yml.

Well. I am guiding someone remotely and the person did say he could not see the `secure` part to add to `.travis.yml`. A new release would be nice.

**Comment by asmeurer** [comment]
Yes, we definitely should do a release, since this causes doctr configure to always crash.

**Comment by asmeurer** [comment]
> Well. I am guiding someone remotely and the person did say he could not see the secure part to add to .travis.yml. A new release would be nice.

Oh you're right. So yeah, we definitely need to release, it's unusable now.

**Comment by asmeurer** [comment]
@gforsyth can you handle the release or do you want me to?

**Comment by gforsyth** [comment]
I can take it

**Comment by gforsyth** [comment]
Hey @ocefpaf -- the new release should be up on PyPI now if you want to continue your remote guidance.  Thanks for spreading the word!

**Comment by ocefpaf** [comment]
Thanks!

**Comment by kyleniemeyer** [comment]
@gforsyth @asmeurer FYI, the conda-force feedstock wasn't updated with the new version—I had originally installed using conda, and ran into this error until I reinstalled via pip.

**Comment by gforsyth** [comment]
Thanks, @kyleniemeyer -- I was waiting for Travis to finish and then just forgot about it. I just merged that in, so it should show up pretty soon in conda-forge
