### ISSUE TITLE
Weird behavior with a pre-existing gh-pages branch

### ISSUE THREAD

**Issue by choldgraf** [drdoctr/doctr#184]
I've experienced some weird behavior of doctr when there's already a gh-pages branch in existence. I think it'd be worth adding a note to users that they should clear out their gh-pages branch before deploying w/ doctr. I can do this in a later PR but putting it here as a note

**Comment by asmeurer** [comment]
That shouldn't be necessary. What was the behavior you were seeing?

**Comment by choldgraf** [comment]
I'm trying to remember because this is actually something I ran into a while back, just didn't get around to opening an issue. I think that I hit some errors when I would use doctr, then somebody would push to the gh-pages branch, then doctr would try to auto-build after that, and it returned a git error. Does that sound like something that could happen? I don't think this is really a bug, more of a thing worth documenting if it's something users could run into

**Comment by asmeurer** [comment]
There is a known issue where there can be race conditions if gh-pages is pushed to between when doctr pulls and pushes (https://github.com/drdoctr/doctr/issues/159). I don't know if that's what you were seeing. We definitely should fully be supporting gh-pages having other stuff not related to doctr.

**Comment by choldgraf** [comment]
I'm gonna close this because I don't think it's a clearly actionable point. I may have been mistaken in my memory but I'll re-open if I run into the issue again
