### ISSUE TITLE
People still think doctr is Sphinx only

### ISSUE THREAD

**Issue by asmeurer** [drdoctr/doctr#195]
Apparently people still think doctr is Sphinx only. We should figure out how to make this clearer in the docs. Maybe remove mentions of Sphinx from the main page. CC @bjodah.

**Comment by bjodah** [comment]
I drew the (obviously erroneous) conclusion from this:
```
  - set -e
  - pip install sphinx doctr
  - cd docs
  - make html
  - cd ..
  - doctr deploy .
```
I was simply thinking:  "since only `.` is given as argument to `doctr deploy` it must be preconfigured to look for a folder called 'docs', and then use _build/html

**Comment by asmeurer** [comment]
I see. We should remove `sphinx` from that line and elsewhere on the front page (except the note that says it doesn't require Sphinx). And add `--built-docs` to all the examples. I actually noticed before that it was odd that `--built-docs` is a flag when the deploy directory isn't. What do you think @gforsyth?
