### ISSUE TITLE
doctr configure should guess that the docs are being built for the current repo

### ISSUE THREAD

**Issue by asmeurer** [drdoctr/doctr#200]
We will probably need to use the GitHub API some here, because some people clone from the original repo and some people clone from their forks, so we have to detect the root (non-fork) repo. 

Although as a first pass, just guessing the repo for `origin` would go a long way.

**Comment by choldgraf** [comment]
if you're thinking github API, just a quick FYI I'd recommend https://github.com/PyGithub/PyGithub

it's documentation is shit, but it's pretty useful :-)
