### ISSUE TITLE
Generate a shell script instead of copy/pasting lines?

### ISSUE THREAD

**Issue by choldgraf** [drdoctr/doctr#207]
I was playing around with getting doctr working on a repository w/ multiple builds, and found that it was kind of a pain in the butt to get working for a few reasons:

1. You really only wanna deploy doctr on a single build (e.g. your 3.6 build)
2. Travis is really weird about handling multi-line if statements

I was thinking - rather than asking users to copy/paste doctr deploy code, what if `doctr configure` created a `.sh` script that had a section for `<path-to-docs-html>` that users could edit and then move to wherever they want. Then the instructions would just be `in your .travis.yml file, add the lines './path/to/deploy_doctr.sh'`. Or something like this. Might simplify the process for some people?

**Comment by asmeurer** [comment]
Can you give an example of what it would output? 

I usually build (and deploy) the docs in a separate build from the tests, and there's only one build for it (it's not that important to me that the docs build in all Python versions, but maybe that could matter for some projects?).

**Comment by asmeurer** [comment]
For example, this is how I have it set up for [sympy](https://github.com/sympy/sympy/blob/281e59ec9ba47be134131b298d51dd278ba88d71/.travis.yml#L310).

**Comment by choldgraf** [comment]
Here's the travis I set up this morning as I was playing around with this:

https://github.com/choldgraf/download/blob/master/.travis.yml

Basically it just checks if the python version is 3.6 `after_success` and then calls the shell script I wrote (w the doctr commands in it) if so.

**Comment by asmeurer** [comment]
How is Travis weird for if statements? It seems to work for us with SymPy. Maybe you need to use the YAML block syntax (like [here](https://github.com/sympy/sympy/blob/281e59ec9ba47be134131b298d51dd278ba88d71/.travis.yml#L275))?

**Comment by choldgraf** [comment]
definitely possible that I was just doing this the wrong way. I tried a few ways that didn't work, then googled it and found a few images where people were complaining about travis not understanding multi-line statements well. However those were from a few years back so maybe it's better. I'll try your method w/ the block syntax, I hadn't tried that yet.

**Comment by asmeurer** [comment]
I do wish Travis had a native YAML syntax for doing things only in specific builds, instead of having to do bash if checks against environment variables. Maybe we should at least add some better docs on how to make doctr only run in one build.

**Comment by choldgraf** [comment]
Just an update, I got this to work with your syntax, so thanks :-)

Re: docs, not a bad idea!

**Comment by choldgraf** [comment]
I'm gonna close this and open an issue w/ a more specific goal #208
