### ISSUE TITLE
DOCTR_DEPLOY_ENCRYPTIOn_KEY not set

### ISSUE THREAD

**Issue by CJ-Wright** [drdoctr/doctr#236]
So I tried to follow all the instructions, but got this error
https://travis-ci.org/xpdAcq/redsky#L934
Here is the [`travis.yml`](https://github.com/xpdAcq/redsky/blob/master/.travis.yml)
Any thoughts on what I am doing wrong?
(I do have the [`github_deploy_key.enc`](https://github.com/xpdAcq/redsky/blob/master/github_deploy_key.enc) that doctr made)

**Comment by asmeurer** [comment]
Same as https://github.com/drdoctr/doctr/issues/161 maybe? I thought I also reported another instance. 

Is this a pull request build?

**Comment by CJ-Wright** [comment]
Yes? I'm not certain what a PR build is? I pulled this in and it's on master and failed on master.

**Comment by asmeurer** [comment]
It looks like it's not. A PR build is a build of a pull request from a fork.

**Comment by CJ-Wright** [comment]
Sorry, the yes was to the "Same as #161 " I think. Is there anything I can do to fix this on my end?

**Comment by asmeurer** [comment]
Actually, I just realized your link isn't to a specific build, but the latest build. Which build was it where you saw the error? Make sure the URL has a build number in it.

**Comment by CJ-Wright** [comment]
Terribly sorry I think this directs to the correct build: https://travis-ci.org/xpdAcq/redsky/builds/256458342#L945

**Comment by asmeurer** [comment]
Does it happen on all builds or just this one? I've seen this issue before where it was intermittent.

If it does happen every time, I would first try regenerating the deploy key (don't forget to delete the old one in your GitHub settings).

Another thing you could try is to install doctr from git (`pip install git+git://github.com/xpdAcq/redsky.git`). We have a lot of changes since the last release. I don't remember if any might help with this issue.

**Comment by CJ-Wright** [comment]
Is there a good way to enable pushing from not master? I feel a bit vulnerable if I have to merge a PR/commit to master to see if the new code works. Does that change the system too much that these fixes may no longer be applicable?

**Comment by asmeurer** [comment]
You'll have to push a branch up (you can't build from a PR from a fork). But yes, it's doable https://drdoctr.github.io/doctr/recipes.html#deploy-docs-from-any-branch.

**Comment by CJ-Wright** [comment]
Cool

**Comment by CJ-Wright** [comment]
@asmeurer you might want to edit [this](https://github.com/drdoctr/doctr/issues/236#issuecomment-317284516) for posterity. I think I should be installing doctr from git not redsky.

**Comment by CJ-Wright** [comment]
This is a problem with the [pip install](https://travis-ci.org/xpdAcq/redsky/builds/256696956#L984) as well.

**Comment by CJ-Wright** [comment]
re-running configure fixed things

**Comment by asmeurer** [comment]
We should note about rerunning configure in the error message.

**Comment by CJ-Wright** [comment]
Fair

**Comment by CJ-Wright** [comment]
I think this is related. This is for https://travis-ci.org/xpdAcq/SHED/jobs/268041605#L1308 which was a repo where doctr had previously worked. Do I need to regen the key again?
`ERROR: The doctr command '/home/travis/mc/envs/testenv/bin/doctr deploy . --built-docs ./docs/_build/html' failed: DOCTR_DEPLOY_ENCRYPTION_KEY environment variable is not set``

**Comment by cmsquared** [comment]
I am having the same issue with missing environment variables for a new project: [most recent failure](https://travis-ci.com/laristra/wonton/jobs/173769174).  This was building the `master` branch, and is using the latest release of doctr, 1.7.4.  The failure is repeatable.  I have also recreated the key, ensuring to delete the previous GitHub deploy key.  The issue persists.

One thing that is not clear to me is where these environment variables get set.  I have another project that is using doctr, set up under similar configuration, but I don't recall having ever set these variables.

**Comment by asmeurer** [comment]
@cmsquared I'm sorry I've been neglecting doctr for a while. I need to finish up some work which would fix this issue. The problem is that you are using travis-ci.com, instead of .org. The latest release of doctr doesn't support it. 

I still need to fix a [couple of things](https://github.com/drdoctr/doctr/issues/335) before doing a release, but I believe it is working in master, so if you want to run that as a workaround in the meantime, I believe it should work.

**Comment by cmsquared** [comment]
@asmeurer Thanks for the feedback.  I just tried running master and I get the same failure, plus the warning about not being able to detect if the repo is a fork.  I'll keep looking into the doctr source to see where things are going awry.

**Comment by asmeurer** [comment]
Be sure to use master both for configure and on Travis. You will need to re-configure.

**Comment by cmsquared** [comment]
Yes, I just came back to say I spoke too soon.  After re-configuring with master, it appears to work.  Thanks!

**Comment by asmeurer** [comment]
Great. That warning can be safely ignored by the way. We should probably just get rid of it.

**Comment by asmeurer** [comment]
@cmsquared I've released doctr 1.8.0 (pip install works now, if you install from conda-forge, you'll need to wait a bit for that to build). You should switch to installing the latest release, and let me know if you have any further issues.

**Comment by cmsquared** [comment]
@asmeurer Thanks for the quick fix.  I'll swap to building the release.
