### ISSUE TITLE
DOC: error in Recipes

### ISSUE THREAD

**Issue by CJ-Wright** [drdoctr/doctr#238]
[This recipe](https://drdoctr.github.io/doctr/recipes.html#deploy-docs-from-any-branch) told me to use the `--gh-pages-docs` flag, but I got the error `doctr: error: The --gh-pages-docs flag is deprecated. Specify the directory to deploy to using 'doctr deploy <dir>'` from [here](https://travis-ci.org/xpdAcq/redsky/builds/256695646#L975)

**Comment by asmeurer** [comment]
Yeah, I noticed that at scipy. Was going to fix it, but didn't get around to it yet.

**Comment by CJ-Wright** [comment]
Sorry for being a human fuzzer

**Comment by asmeurer** [comment]
Also I already had an issue for it. Closing this as a dupe https://github.com/drdoctr/doctr/issues/226

**Comment by CJ-Wright** [comment]
Thank you!
