### ISSUE TITLE
Doctr deploy bails on conflicts

### ISSUE THREAD

**Issue by scopatz** [drdoctr/doctr#244]
Hi All, I am seeing the following issue: https://travis-ci.org/ergs/rg-db-public/builds/268061109?utm_source=email&utm_medium=notification

```
The doctr command that was run is
    /home/travis/miniconda/bin/doctr deploy --deploy-repo ergs/ergs.github.io --deploy-branch-name master --built-docs website/_build/html .
'
[master 43c983e] Update docs after building Travis build 10 of ergs/rg-db-public
....
Pulling
git pull doctr_remote master
Auto-merging people/scopatz.html
CONFLICT (add/add): Merge conflict in people/scopatz.html
Auto-merging people/hodge.html
CONFLICT (add/add): Merge conflict in people/hodge.html
Auto-merging people/asmeurer.html
CONFLICT (add/add): Merge conflict in people/asmeurer.html
Auto-merging blog/rss.xml
CONFLICT (add/add): Merge conflict in blog/rss.xml
Auto-merging README.md
CONFLICT (add/add): Merge conflict in README.md
Automatic merge failed; fix conflicts and then commit the result.
```

The `doctr deploy -h` docs didn't present any obvious answers. Is there a way around this? I prefer to have the docs that were just built pushed.

**Comment by scopatz** [comment]
Thanks in advance!

**Comment by gforsyth** [comment]
Hey @scopatz -- I don't think we have a way to handle this right now.  I know I was originally thinking that only `doctr` would be pushing to a `gh-pages` branch (or equivalent) but I see that you also have `regolith` updating some things on your end.

I guess we could add a flag to force push if there are merge conflicts? 

Short term to get ergs up-to-date, you could build the docs locally and then force-push them?

**Comment by scopatz** [comment]
> I guess we could add a flag to force push if there are merge conflicts?

That would be great!

> Short term to get ergs up-to-date, you could build the docs locally and then force-push them?

This isn't urgent, but it would definitely be nice to have.  It would be great if doctr could handle this (more general) use case!

**Comment by asmeurer** [comment]
This should be fixed on master. You can try installing doctr from master to test if you want. We should do a release soon but we need to clear up some things first.

**Comment by asmeurer** [comment]
To clarify, in master doctr merges with the "ours" strategy, so it should avoid conflicts.

**Comment by scopatz** [comment]
Yeah, I thought we had looked at this issue at one point @asmeurer. Not super interested in working from master for that repo. I think I'll sit tight until the release, when this issue can be closed. Thanks!

**Comment by asmeurer** [comment]
Should be fixed in the latest release. Please open a new issue if you still see this with 1.6.0.
