### ISSUE TITLE
Broken Webdocs?

### ISSUE THREAD

**Issue by CJ-Wright** [drdoctr/doctr#245]
I think the webdocs are broken?
https://drdoctr.github.io/doctr/

**Comment by asmeurer** [comment]
The last commit on gh-pages was a week ago https://github.com/drdoctr/doctr/commits/gh-pages.

**Comment by asmeurer** [comment]
Looks like https://drdoctr.github.io/doctr/docs/ works

**Comment by CJ-Wright** [comment]
That's wild? Would you mind changing it in the GitHub subtitle bar thing? (if that is what you want to go with)

**Comment by asmeurer** [comment]
Oh that most recent commit on gh-pages actually broke it. Going to manually revert until we can figure this out.

**Comment by CJ-Wright** [comment]
Cool thank you!

**Comment by asmeurer** [comment]
OK, the site works again. What the hell happened?

**Comment by CJ-Wright** [comment]
:man_shrugging:
