### ISSUE TITLE
Support username.github.io style GitHub pages

### ISSUE THREAD

**Issue by asmeurer** [drdoctr/doctr#25]
There are two kinds of GitHub pages, user/org pages, and project pages. User/org pages are in repos named `username.github.io`, and are deployed to the `master` branch. Project pages are in any repo, and are deployed to the `gh-pages` branch. We currently support the latter. Supporting the former wouldn't be hard, maybe even detecting it automatically. 

This is low priority (I don't personally have a need for it).

**Comment by gforsyth** [comment]
Hey @asmeurer -- we're moving the xonsh docs to live under the xonsh organization and @Carreau has set up a `xonsh.github.io` style repo to host it.  If #54 is updated, then I can add in the `github.io` support and we can test it out with the xonsh docs (if @Carreau is amenable to this)

**Comment by asmeurer** [comment]
#54 is next on my todo list for doctr, after 1.1.1, since that is how we deploy docs for SymPy.

**Comment by gforsyth** [comment]
Implemented in #168
