### ISSUE TITLE
Pushing to gh-pages instead of master

### ISSUE THREAD

**Issue by scopatz** [drdoctr/doctr#253]
As can be seen in [this build](https://travis-ci.org/ergs/website/builds/271288507#L1403), doctr is currently pushing to gh-pages on a `*.github.io` repo. The docs for `doctr deploy` say,

```
  --deploy-branch-name DEPLOY_BRANCH_NAME
                        Name of the branch to deploy to (default: 'master' for
                        ``*.github.io`` repos, 'gh-pages' otherwise)
```

Worse, when I try to manually set `--deploy-branch-name master`, the doctr dies on me, as [seen here](https://travis-ci.org/ergs/website/builds/271288166#L1467).

**Comment by asmeurer** [comment]
Might be fixed in master (you'll have to test it).

**Comment by scopatz** [comment]
Thanks @asmeurer - I guess I'll wait until the next release then.  Any idea of when that'll be?

**Comment by asmeurer** [comment]
I'll try to work on it this next week.

**Comment by scopatz** [comment]
thanks!

**Comment by asmeurer** [comment]
I've released a new version of doctr. Please open a new issue if this is still a problem.
