### ISSUE TITLE
remote git ignored files can't be added on travis

### ISSUE THREAD

**Issue by fredRos** [drdoctr/doctr#257]
doctor fails on travis, presumably because some files in the docs are git ignored and can't be added

```
Switched to a new branch 'gh-pages'

The following paths are ignored by one of your .gitignore files:

examples/markov_chain.hires.png

Use -f if you really want to add them.

...

git add ./examples/markov_chain.hires.png
```
and that command fails, so the build stop. [Full log](https://travis-ci.org/fredRos/pypmc/jobs/279533914)

I checked on my desktop why this file is ignored with `git check-ignore -v doc/_build/examples/markov_chain.hires.png` and removed the corresponding line from the `.gitignore`. I can locally add the `png` w/o error. The build on travis still [fails](https://travis-ci.org/fredRos/pypmc/jobs/279838792). As before, it warns about the `png` file but stops at a different position

```
The following paths are ignored by one of your .gitignore files:

examples/markov_chain.hires.png

Use -f if you really want to add them.

Setting git attributes

git config --global user.name 'Doctr (Travis CI)'

git config --global u
```

Finally I removed the `.gitignore` altogether but the build still failed with the same output. After some trying around, I thought it must be due to the remote `gh-pages` branch on github, so I removed that and just triggered a rebuild on travis and finally the deployment succeeded. I think I initially created a `gh-pages` by cloning the master branch but I'm not sure. 

This ignore-file problem was quite a stumbling block for me. Perhaps you can update doctr or its docs to indicate what to do in this situation.

**Comment by asmeurer** [comment]
These sound like issues that have already been fixed in master. 

I'm going to do a release soon (https://github.com/drdoctr/doctr/pull/254). I was going to do it earlier but I didn't get around to it. 

If you want, you can test the git version of doctr. Otherwise, please try again after I do the release and let me know if you still have issues.

**Comment by fredRos** [comment]
Well it sounds like this could be a useful feature to have a `.gitignore` that doesn't get overwritten by doctr. It was just hard to find out that the remote `.gitignore` was used instead of the one in the master branch. An informative error message would have done the job.

**Comment by asmeurer** [comment]
OK, I've made a release. Can you try again (trigger a new build), and let me know if it still fails.

**Comment by fredRos** [comment]
Thank you very much. I triggered a new build so there was no new file but doctr did not fail despite a `.gitignore` in `gh-pages` branch. Good job!
