### ISSUE TITLE
Does there need to be an already existing gh-pages branch on the repo?

### ISSUE THREAD

**Issue by arokem** [drdoctr/doctr#271]
I've used `doctr configure` on a repo that had github pages set up to render the documentation from `master` (we were displaying the readme file). Now, when I push doctr up, I get this: https://travis-ci.org/yeatmanlab/AFQ-Browser/jobs/293486945#L818. Does the repo have to already have a `gh-pages` branch in advance for doctr to work?

**Comment by asmeurer** [comment]
It's supposed to create it for you, but we also don't have a test for that, so it probably broke at some point.

**Comment by asmeurer** [comment]
For some reason it's not running this line https://github.com/drdoctr/doctr/blob/466c77f463ecf807ca484434eaa9650e3cf6ebe6/doctr/travis.py#L313 but I can't tell why because push should be True as far as I can tell (the other `canpush=True` stuff is running).

**Comment by asmeurer** [comment]
Oh scratch that, it isn't https://travis-ci.org/yeatmanlab/AFQ-Browser/jobs/293486945#L720.

**Comment by asmeurer** [comment]
Oh this is a pull request build. So it looks like the detection of pushing is working, but it does the wrong thing when gh-pages doesn't exist and you can't push. 

Fix at https://github.com/drdoctr/doctr/pull/272.

**Comment by asmeurer** [comment]
@arokem the build *should* work if you merge the PR (assuming you did `doctr configure` correctly). If you don't want to do that with a failing Travis build I can try to get a bugfix release out as soon as I get that PR fully tested.

**Comment by arokem** [comment]
Thanks! That's helpful. I guess we'll go ahead and merge that, and clean up
afterwards...
