### ISSUE TITLE
Ability to do something different on a tag

### ISSUE THREAD

**Issue by asmeurer** [drdoctr/doctr#29]
This tool is mainly designed for uploading dev docs, but it can also be used to upload release docs. In that case, we might need some way to do something different on a tag. 

Or maybe the logic for uploading on a tag should just go in the individual .travis.yml files, in which case we can at least document what it could look like.

**Comment by dopplershift** [comment]
At the very least, it would be nice to allow (out of the box) building only on master AND tags.
