### ISSUE TITLE
Doctr configure command doesn't work locally on Windows due to lack of native ssh-keygen executable

### ISSUE THREAD

**Issue by CAM-Gerlach** [drdoctr/doctr#301]
I'm a contributor with the [Spyder IDE](https://github.com/spyder-ide), and we're currently completing the process of transitioning our docs to be deployed using ``doctr`` (I'll send a PR to add our name as soon as they officially are declared production-status very soon). When running ``doctr configure`` on Windows, key generation failed due to it being unable to find a ``ssh-keygen`` binary on the PATH. Therefore, it seems ``doctr`` presumes it is being run on a *nix system with this available, even though this is not indicated anywhere I could find in the documentation and unfortunately, a significant portion of developers are stuck on Windows for one reason or another. 

After figuring out the root cause of the issue, I was able to hack a quick fix by adding the appropriate directory from my ``msysgit`` install to the $PATH$ first which had it (presumably my Cygwin install would have worked too, or anything else that had that binary). However, this obviously is pretty poor Ux for a new user, if this is in fact a problem for any Windows user that doesn't have some sort of ``msys`` install or the like on their path.

Therefore, at minimum, the documentation should presumably be updated to reflect this and the fix, or perhaps a more sustainable solution could be devised (e.g. autodetecting an existing ``MSYS`` install like with GfW or Cygwin, etc. or perhaps even WSL, and if not notifying the user interactively of the problem and how to fix it. Thanks!

**Comment by asmeurer** [comment]
Windows support would be great. I don't have a Windows machine to test with, which is why it isn't there yet. We do need to be able to generate an ssh key. If you want to make a pull request to support it I'll accept it.

**Comment by CAM-Gerlach** [comment]
@asmeurer It worked just fine on my Windows machine once I added ``usr/bin/`` from my GfW install to my $PATH$, giving it access to ssh-keygen. Since you can't just bundle ``ssh-keygen`` since its GPL, I could implement and test the following:

* Automatically search likely paths (``%ProgramFiles%/Git/usr/bin``, etc) for a ``ssh-keygen`` executable to use if its not already found on the $PATH$ (and possibly others if needed)
* If not, prompt the user to download GfW or otherwise put a ``ssh-keygen`` executable somewhere on the $PATH$.
* Mention something to this effect in the documentation

Not sure I can get to it right away, since I have a long to-do list for Spyder, but it shouldn't be too hard at all even for a relative newbie like me. In the meantime, though, it would probably be best from a UX perspective to put something in the docs/readme about no official Windows support and how to get around it since it was quite confusing and frustrating to be hit with the error when lack of windows support/only Linux was never mentioned anywhere that I saw.

**Comment by CAM-Gerlach** [comment]
You can assign the issue to me if you'd like, to keep track.

**Comment by asmeurer** [comment]
By the way, we may be able to just generate the key using `cryptography`, which would not require ssh on Windows at all (see https://stackoverflow.com/questions/2466401/how-to-generate-ssh-key-pairs-with-python).

**Comment by CAM-Gerlach** [comment]
That would be a better long-term solution, for sure. It would be (somewhat) more work and testing, and you'd be better equipt to implement it than I if you decided to take that route immediately. Otherwise, I can implement the above as a stopgap.

**Comment by asmeurer** [comment]
Yeah, I'll try to get to it. I don't know when I will, though, so in the meantime a documentation improvement would be welcome.

**Comment by asmeurer** [comment]
@CAM-Gerlach I've released doctr 1.7.3 which uses `cryptography` to generate the SSH key (available via pip now and conda-forge shortly). Let us know if you have any more difficulties running `doctr configure` on Windows.

**Comment by asmeurer** [comment]
I just realized the color output will be messed up on Windows unless you use a bash shell. Maybe we should depend on colorama instead of hard-coding our color functions.

**Comment by CAM-Gerlach** [comment]
@asmeurer Thanks! I just got to testing it now, and everything appeared to work perfectly. The colors look fine to me, even in the ye olde ``cmd`` shell instead of ``git bash``, but maybe that's because I use Conemu instead of the horrid default emulator: (Btw that's not our real deploy key ofc, just one generated for testing)

![image](https://user-images.githubusercontent.com/17051931/39076908-e06b8ece-44c3-11e8-81f1-8f4cbc809ff1.png)

**Comment by asmeurer** [comment]
Great. The colors look correct to me. 

The deploy key printed to the screen is public (it goes in .travis.yml). The private key is never shown to the user. It's encrypted to a file and can only be decrypted on Travis.
