### ISSUE TITLE
Is it possible to have static generator source files in branch other than master for a username/orgname.github.io site?

### ISSUE THREAD

**Issue by moorepants** [drdoctr/doctr#314]
I'm using doctr with an orgname.github.io site along with pelican. It seems that these sites require the html to be in the master branch. Is it possible to set the default github branch to a branch specifically setup to hold the pelican input files and serve only the generated html on the master branch? I'd like to keep the source separate from the output in some way for a orgname.github.io page. It isn't clear to me if this is possible or how to do it.

**Comment by asmeurer** [comment]
Yep. This is how we have it for https://github.com/sympy/sympy.github.com. Go to the settings for your repo under "branches" and change the default branch. You have to make the default branch something other than `master` because .github.io pages have to be served under master (see https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/). 

Probably worth documenting this in our docs somewhere, perhaps as a [recipe](https://drdoctr.github.io/recipes.html).

**Comment by moorepants** [comment]
I thought I did this, but travis got into an endless loop: https://travis-ci.org/mechmotum/mechmotum.github.io/builds

Seems like each travis build caused a new travis build. Not quite sure what is going on.

**Comment by asmeurer** [comment]
You need to disable Travis on master if you do this (delete the .travis.yml).

**Comment by asmeurer** [comment]
I wonder if we should support this use-case. Doctr would just need to detect if the commit it is built from is its own commit and stop. It would sill trigger an additional build every time it pushes, but it wouldn't loop forever. At the very least, it would prevent this from happening by accident. 

Either way, we definitely need to document this.

**Comment by moorepants** [comment]
Yes! Ha. .travis.yml in each branch created the circular builds.

**Comment by moorepants** [comment]
I setup the new default branch with the sources but when commit are merged there it doesnt' seem like doctr pushes the output files to the master branch anymore.

**Comment by asmeurer** [comment]
Ah, forgot one more thing. You need to add `--branch-whitelist sources` to the doctr command (replace `sources` with the name of your branch). See for instance https://github.com/sympy/sympy.github.com/blob/138cb0be2ab9245caa9fc1680776869f658e73a8/.travis.yml#L14.

**Comment by moorepants** [comment]
Thanks. Yes, this does warrant a recipe. I've boogered it up in multiple ways. I can try to draft something and submit.

**Comment by asmeurer** [comment]
We could also have a better message when a branch isn't in the whitelist.

**Comment by moorepants** [comment]
Closing.
