### ISSUE TITLE
doctr with lots of files in docs

### ISSUE THREAD

**Issue by thequackdaddy** [drdoctr/doctr#324]
So we sucessfully set up doctr to generate the documentation for statsmodels. Cool tool, I like it. 

However, statsmodels generates lots, and lots, and lots of files for itss docs. 

It looks like doctr is taking about 20 minutes to cycle through the `git add file` here:

https://github.com/drdoctr/doctr/blob/5067c1e28ef446ef058157bce2441554a2710588/doctr/travis.py#L477-L482

Any ideas how to speed this up?

**Comment by thequackdaddy** [comment]
Here's an example merge commit... it finishes with only a few minutes before the 50 minute travis limit...

https://travis-ci.org/statsmodels/statsmodels/builds/430288369

**Comment by asmeurer** [comment]
Maybe we can run one giant git add instead. We could also probably use some other git commands to detect which files are changed or untracked and only add those.

**Comment by bashtage** [comment]
@asmeurer Do you have any plans for a release in the near future? statsmodels is very close on Travis to the limit (typically ~46 minutes) and it would be good to get the git add improvements in. 

If you aren't going to release we could clone git -- but a release is preferred.

**Comment by gforsyth** [comment]
I can cut a new release this evening (ET) if @asmeurer doesn't get to it before then.

**Comment by asmeurer** [comment]
I was going to do it. I want to take a look at the other PRs first. We probably should hold off on the travis-ci.com stuff, but the others can likely go in.

**Comment by asmeurer** [comment]
Actually just https://github.com/drdoctr/doctr/pull/320 is probably ready to go.

**Comment by bashtage** [comment]
Thanks both.

**Comment by asmeurer** [comment]
1.7.4 release is out on PyPI now and will be on conda-forge later. https://drdoctr.github.io/changelog.html
