### ISSUE TITLE
Support new authentication for GitHub

### ISSUE THREAD

**Issue by asmeurer** [drdoctr/doctr#369]
Our GitHub authentication method is deprecated and will go away in November. See https://github.blog/2020-07-30-token-authentication-requirements-for-api-and-git-operations/ and https://twitter.com/patricktoomey/status/1289019204662972419. The simplest way is to have people generate a token, although we should try to do the localhost callback or device authorization flow if we can.

**Comment by peterjc** [comment]
Tokens provided via a TravisCI protected environment variable work well, see #349 - sadly I have not made time to finish that.

**Comment by asmeurer** [comment]
This is about `doctr configure`. As far as I know, the behavior of `doctr deploy` should continue to work as it currently is.

**Comment by asmeurer** [comment]
So GitHub has dropped support. `doctr configure` now fails with `invalid username or password` even if you enter the correct password.
