### ISSUE TITLE
Move to a github organization?

### ISSUE THREAD

**Issue by gforsyth** [drdoctr/doctr#67]
`doctravis` is available.  
other options:
`drdoctr`
`rtcod`
`youwillfeelasmallpinch`

**Comment by asmeurer** [comment]
`rtcod` is just evil

**Comment by asmeurer** [comment]
I like `drdoctr`, although I would feel strongly compelled to create a subrepository called `givemethenews`.

**Comment by gforsyth** [comment]
Ok, sounds good to me.

**Comment by gforsyth** [comment]
organization created and I sent you an invite.  I won't transfer the repo just yet -- maybe we want to wait until we have `github.io` support working?

**Comment by asmeurer** [comment]
Maybe we should add support to deploy to multiple destinations, so that we can test all three. Right now, you can only deploy to one place because there can only be one environment variable with the decryption key.
