### ISSUE TITLE
GitHub pages can be on the master branch now

### ISSUE THREAD

**Issue by asmeurer** [drdoctr/doctr#86]
https://github.com/blog/2228-simpler-github-pages-publishing

**Comment by asmeurer** [comment]
https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

**Comment by asmeurer** [comment]
I guess this validates the use of `docs` as the default option for `--gh-pages-docs`.

**Comment by asmeurer** [comment]
Deploying dev docs to the same repo to the master branch seems like a really bad idea. It would pollute the master branch with a bunch of auto-generated deploy commits, and you wouldn't be able to enable branch protection with required checks on master. It could make sense for a separate deploy repo, although whether the default branch is named "master" or "gh-pages" seems pretty immaterial.

So in other words, I guess we should support this, but it actually seems like a bad idea to me to use doctr to deploy to your master branch. Maybe we should just wait until someone actually requests it to implement it (or sends a PR).

**Comment by gforsyth** [comment]
> So in other words, I guess we should support this, but it actually seems like a bad idea to me to use doctr to deploy to your master branch. Maybe we should just wait until someone actually requests it to implement it (or sends a PR). 

agreed.

**Comment by gforsyth** [comment]
Implemented in #164
